<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main"/>
		<link rel="stylesheet" href="${resource(dir:'js/datepicker',file:'datepicker.css')}" type="text/css" />
		<link rel="stylesheet" href="${resource(dir:'js/slider/',file:'slider.css')}" type="text/css" />
		<link rel="stylesheet" href="${resource(dir:'js/chosen/',file:'chosen.css')}" type="text/css" /> 
	</head>
	<body>
	
<section class="panel panel-default">
    <header class="panel-heading font-bold"> Form elements </header>
    <div class="panel-body">
        <form class="form-horizontal" method="get">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control">
                            <span class="help-block m-b-none">Add a title for your next event ! Sublime .</span>
                        </div>
                    </div>
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    <div class="line line-dashed b-b line-lg pull-in"></div>
                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                        <label class="col-sm-2 control-label">Started</label>
                                                                                                                                                                                                                                                                        <div class="col-sm-10">
                                                                                                                                                                                                                                                                            <label class="switch">
                                                                                                                                                                                                                                                                                <input type="checkbox">
                                                                                                                                                                                                                                                                                    <span></span>
                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                <div class="line line-dashed b-b line-lg pull-in"></div>
                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                    <label class="col-sm-2 control-label">Start Date</label>
                                                                                                                                                                                                                                                                                    <div class="col-sm-10">
                                                                                                                                                                                                                                                                                        <input class="input-sm input-s datepicker-input form-control" size="16" type="text" value="12-02-2013" data-date-format="dd-mm-yyyy">
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                    <label class="col-sm-2 control-label">End Date</label>
                                                                                                                                                                                                                                                                                    <div class="col-sm-10">
                                                                                                                                                                                                                                                                                        <input class="input-sm input-s datepicker-input form-control" size="16" type="text" value="12-02-2013" data-date-format="dd-mm-yyyy">
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                            <div class="line line-dashed b-b line-lg pull-in"></div>
                                                                                                                                                                                                                                                                                            <div class="form-group">
                                                                                                                                                                                                                                                                                                <label class="col-sm-2 control-label">Wysiwyg</label>
                                                                                                                                                                                                                                                                                                <div class="col-sm-10">
                                                                                                                                                                                                                                                                                                    <div class="btn-toolbar m-b-sm btn-editor" data-role="editor-toolbar" data-target="#editor">
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Font">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-font"></i>
                                                                                                                                                                                                                                                                                                                <b class="caret"></b>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <ul class="dropdown-menu">
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Serif" style="font-family:'Serif'">Serif</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Sans" style="font-family:'Sans'">Sans</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Arial" style="font-family:'Arial'">Arial</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Arial Black" style="font-family:'Arial Black'">Arial Black</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Courier" style="font-family:'Courier'">Courier</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Courier New" style="font-family:'Courier New'">Courier New</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Comic Sans MS" style="font-family:'Comic Sans MS'">Comic Sans MS</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Helvetica" style="font-family:'Helvetica'">Helvetica</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Impact" style="font-family:'Impact'">Impact</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Lucida Grande" style="font-family:'Lucida Grande'">Lucida Grande</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Lucida Sans" style="font-family:'Lucida Sans'">Lucida Sans</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Tahoma" style="font-family:'Tahoma'">Tahoma</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Times" style="font-family:'Times'">Times</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Times New Roman" style="font-family:'Times New Roman'">Times New Roman</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontName Verdana" style="font-family:'Verdana'">Verdana</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Font Size">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-text-height"></i>&nbsp;
                                                                                                                                                                                                                                                                                                                <b class="caret"></b>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <ul class="dropdown-menu">
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontSize 5" style="font-size:24px">Huge</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontSize 3" style="font-size:18px">Normal</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                    <a data-edit="fontSize 1" style="font-size:14px">Small</a>
                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="bold" title="" data-original-title="Bold (Ctrl/Cmd+B)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-bold"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="italic" title="" data-original-title="Italic (Ctrl/Cmd+I)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-italic"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="strikethrough" title="" data-original-title="Strikethrough">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-strikethrough"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="underline" title="" data-original-title="Underline (Ctrl/Cmd+U)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-underline"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="insertunorderedlist" title="" data-original-title="Bullet list">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-list-ul"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="insertorderedlist" title="" data-original-title="Number list">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-list-ol"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="outdent" title="" data-original-title="Reduce indent (Shift+Tab)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-dedent"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="indent" title="" data-original-title="Indent (Tab)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-indent"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="justifyleft" title="" data-original-title="Align Left (Ctrl/Cmd+L)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-align-left"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="justifycenter" title="" data-original-title="Center (Ctrl/Cmd+E)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-align-center"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="justifyright" title="" data-original-title="Align Right (Ctrl/Cmd+R)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-align-right"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm" data-edit="justifyfull" title="" data-original-title="Justify (Ctrl/Cmd+J)">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-align-justify"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        <div class="btn-group">
                                                                                                                                                                                                                                                                                                            <a class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" title="" data-original-title="Hyperlink">
                                                                                                                                                                                                                                                                                                                <i class="fa fa-link"></i>
                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                            <div class="dropdown-menu">
                                                                                                                                                                                                                                                                                                                <div class="input-group m-l-xs m-r-xs">
                                                                                                                                                                                                                                                                                                                    <input class="form-control input-sm" placeholder="URL" type="text" data-edit="createLink">
                                                                                                                                                                                                                                                                                                                        <div class="input-group-btn">
                                                                                                                                                                                                                                                                                                                            <button class="btn btn-default btn-sm" type="button">Add</button>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                <a class="btn btn-default btn-sm" data-edit="unlink" title="" data-original-title="Remove Hyperlink">
                                                                                                                                                                                                                                                                                                                    <i class="fa fa-cut"></i>
                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                            <div class="btn-group hide">
                                                                                                                                                                                                                                                                                                                <a class="btn btn-default btn-sm" title="" id="pictureBtn" data-original-title="Insert picture (or just drag &amp; drop)">
                                                                                                                                                                                                                                                                                                                    <i class="fa fa-picture-o"></i>
                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" style="opacity: 0; position: absolute; top: 0px; left: 0px; width: 0px; height: 0px;">
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                <div class="btn-group">
                                                                                                                                                                                                                                                                                                                    <a class="btn btn-default btn-sm" data-edit="undo" title="" data-original-title="Undo (Ctrl/Cmd+Z)">
                                                                                                                                                                                                                                                                                                                        <i class="fa fa-undo"></i>
                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                    <a class="btn btn-default btn-sm" data-edit="redo" title="" data-original-title="Redo (Ctrl/Cmd+Y)">
                                                                                                                                                                                                                                                                                                                        <i class="fa fa-repeat"></i>
                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                            <div id="editor" class="form-control" style="overflow:scroll;height:150px;max-height:150px" contenteditable="true"> Go ahead… </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                    <div class="line line-dashed b-b line-lg pull-in"></div>
                                                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                                                        <label class="col-sm-2 control-label">Drag and Drop</label>
                                                                                                                                                                                                                                                                                                        <div class="col-sm-10">
                                                                                                                                                                                                                                                                                                            <div class="dropfile visible-lg">
                                                                                                                                                                                                                                                                                                                <small>Drag and Drop file here</small>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                    <div class="line line-dashed b-b line-lg pull-in"></div>
                                                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                                                        <div class="col-sm-4 col-sm-offset-2">
                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-default">Cancel</button>
                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                        </section>	
	

	<!-- Bootstrap -->
	<!-- App -->
	<script type="text/javascript" src="${resource(dir:'js',file:'app.v1.js')}"></script>
	<!-- datepicker -->
	<script type="text/javascript" src="${resource(dir:'js/datepicker',file:'bootstrap-datepicker.js')}"></script>
	<!-- slider -->
	<script type="text/javascript" src="${resource(dir:'js/slider',file:'bootstrap-slider.js')}"></script>
	<!-- file input -->
	<script type="text/javascript" src="${resource(dir:'js/file-input',file:'bootstrap-filestyle.min.js')}"></script>
	<!-- wysiwyg -->
	<script type="text/javascript" src="${resource(dir:'js/wysiwyg',file:'jquery.hotkeys.js')}"></script>
	<script type="text/javascript" src="${resource(dir:'js/wysiwyg',file:'bootstrap-wysiwyg.js')}"></script>
	<script type="text/javascript" src="${resource(dir:'js/wysiwyg',file:'demo.js')}"></script>
	<!-- chosen -->
	<script type="text/javascript" src="${resource(dir:'js/chosen',file:'chosen.jquery.min.js')}"></script>
	<!-- global -->
	<script type="text/javascript" src="${resource(dir:'js',file:'app.plugin.js')}"></script>
	<script type="text/javascript" src="${resource(dir:'js',file:'socket.io-1.0.6.js')}"></script>
	</body>
</html>